### PR TITLE
Ml edit event

### PR DESCRIPTION
**Pull request by mjleavell**
#24 #25 
things to test
- editing a new message
- editing a message from json
- clearing out messages, add a new message, then edit that message
- when you edit a message, the user dropdown should be disabled (user appears but you cant change user, color of dropdown doesnt change)

### CODE REVIEW

**Comment by mjleavell** [comment]
@MCrank @m-khezri @lancehamilton24  hold off on this PR until mohammad's PR (#54) is done

**Comment by MCrank** [comment]
@mjleavell Just running through the code. A couple of small things that I think would be very nice to add.

- When we put the edited text in the input field I think we should set the focus to the input field.  Right now I have to click into the field before I can edit

> getEdittedMsg in chattyMsg.js add `msgInput.focus()` after `msgInput.value = messagesArray[msgIndex].msg;`

- Not a must but what do you think about changing the border of the input field to green when you hit the edit button to bring attention to the fact that your message is back up there for you to edit?  Just a thought and would require us to set the border back to normal.  I think is just replacing a class on the input.  Similar to my validation function in utils.js

**Comment by MCrank** [comment]
👍 🦄 👍 🦄 
Looks great

**Comment by m-khezri** [comment]
Good Job 👍 It works awesome. 
UX Note: In Edit mode, the 'Select User' button doesn't look like a disabled button (paled green color) It's still bright green so users might think it still clickable.

**Comment by mjleavell** [comment]
@m-khezri Yes, I noticed that about the disabled button. It stays that green because it is "success". I will look into making it a paler green, but I am going to go ahead and merge this

**Pull request merged**
