### PR TITLE
fixed bug; need to add enableBtn function to the event listener for e…

### PR DESCRIPTION
**Pull request by mjleavell**
…nter  #46  #22 
- will need to add the enable button function on util.js when message is entered and the message-output is empty. 
- made enable and disable functions usable for other buttons, so i put them on the util.js page

### CODE REVIEW

**Comment by mjleavell** [comment]
@MCrank @m-khezri @lancehamilton24 hold off on this until marco merges his PR. Want to make sure problem is addressed first.

**Comment by mjleavell** [comment]
Ready for review.

**Comment by lancehamilton24** [comment]
👍

**Comment by MCrank** [comment]
👍 Had some issues initially but it started working and am not able to break it again.

**Pull request merged**
